# Cloudflare Pages configuration
[build]
  # Build command for the frontend
  command = "cd frontend && npm install && npm run build"
  
  # Output directory (relative to project root)
  publish = "frontend/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"

  # NPM version
  NPM_VERSION = "10"

# Environment variables for production
[env.production]
  VITE_API_URL = "https://aim-backend-pg2h.onrender.com"
  VITE_SOCKET_URL = "https://aim-backend-pg2h.onrender.com"

# Environment variables for preview
[env.preview]
  VITE_API_URL = "https://aim-backend-pg2h.onrender.com"
  VITE_SOCKET_URL = "https://aim-backend-pg2h.onrender.com"

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' wss: https:; font-src 'self' data:; media-src 'self' data:;"
